<Project Sdk="Godot.NET.Sdk/4.4.0">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>12</LangVersion>

		<Description>Includes types and data objects for Godot that other Petra libraries are likely to use and to easily configure these within the Godot inspector</Description>
		<PackageTags>OpenSourceKingdom, OpenSource, Petra, Game, Framework, Suite, Tool, Primitive, Data, Object, Identifier</PackageTags>
		<Title>OSK.Petra.Godot.Primitives</Title>
		<Authors>BlankDev117</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/OpenSourceKingdom/OSK.Petra.Godot.Primitives</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<!-- Required Godot injection -->
	<ItemGroup>
		<Compile Update="**\*.cs" Pack="true" PackagePath="godot\%(RecursiveDir)%(Filename)%(Extension)" />
		<None Include="..\OSK.Petra.Godot.targets" Pack="true" PackagePath="buildTransitive\$(MSBuildProjectName).targets" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="OSK.Petra.Godot.Framework.Build" Version="0.1.1" />
	</ItemGroup>
</Project>
