<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<ItemGroup Condition="Exists('$(ProjectDir)project.godot')">
		<PetraPackages Include="$(MSBuildThisFileName)" />
		<PetraGodotFiles Include="$(MSBuildThisFileDirectory)..\godot\**\*.*">
			<DestFolder>$(ProjectDir)PetraFramework\$(MSBuildThisFileName)\</DestFolder>
		</PetraGodotFiles>
	</ItemGroup>

</Project>